<?php
/**
 * Package CMS
 * Syntax Phalcon 2.0
 * Owner: system-work.com
 * Author: Sebastian Rzeszowicz * Date: 5/5/2015
 *
 * Segment: View
 * Object: Users
 * Elements: password
*/
// view styles
echo $this->assets->outputCss( 'userFormCss' );

// For higher than admin shows pager
if ( $access[$role] >= $access[ ROLE_ADMIN ] ) {
?>
<ul class="pager">
	<li class="previous pull-left">
		<a href="/user/index" >&larr; <?php echo LABEL_USER_LIST; ?></a>
	</li>
</ul>
<?php } ?>

<?php
// Display menu tabs
echo $this->menus->getTabs( 'user', $id);

// Password reset form
// Old Password
// New Password
// Repeat password
?>
<form action="/user/savePassword/<?php echo $id; ?>" role="form" method="post" class="form-login">

	<h2 class="form-login-heading"><?php echo LABEL_UPDATE_PASSWORD; ?></h2>

	<fieldset>
		<?php echo $form->render("oldPassword");?>
		<?php echo $form->render("newPassword");?>
		<?php echo $form->render("repeatPassword");?>
	</fieldset>

	<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo LABEL_SAVE; ?></button>
</form>
