<?php
/**
 * Package CMS
 * Syntax Phalcon 2.0
 * Owner: system-work.com
 * Author: Sebastian Rzeszowicz
 * Date: 5/5/2015
 *
 * Segment: View
 * Object: Layout
 * Elements: Base
*/
?>
<!doctype html>
<html lang = "en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php
	// Title
	echo $this->tag->getTitle(); ?>
	
	<?php
	// Css styles
	echo $this->assets->outputCss( 'style' ); ?>
	<link rel="stylesheet" type="text/css" href="/third-party/bootstrap.js/css/bootstrap.min.css">
	
	<?php
	// Scripts
	echo $this->assets->outputJs( 'script' ); ?>
</head>

<body>

<?php // Top menu  ?>
	<nav class="navbar navbar-default navbar-inverse" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><?php echo LABEL_BRAND; ?></a>
			</div>

			<?php 
			// Generate menu
			echo $this->menus->getMenu(); ?>

		</div>
	</nav>
<?php // Page content ?>
	<div class="container">

<?php // not authorized visitors get login form only
if ( !empty($Oauth['role']) && $Oauth['role'] == ROLE_GUEST ) { 

	// apply form styles
	echo $this->assets->outputCss( 'userFormCss' ); ?>

<?php 
	// Login form
	// Username
	// Email address
?>
		<form action="/session/start" role="form" method="post" class="form-login">
			<h2 class="form-login-heading"><?php echo LABEL_PLEASE_SIGNIN; ?></h2>
			<fieldset>
				<?php echo $form->render("email");?>
				<?php echo $form->render("password");?>
			</fieldset>

			<button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo LABEL_SIGNIN; ?></button>
		</form>
<?php 
} 
else {
// all authorized visitors get user interface -->
	echo $this->flash->output();
	echo $this->getContent();
	echo '<hr/>';
} ?>

		<footer>
			<p>&copy; <?php echo LABEL_APP_COPYRIGHT;?></p>
		</footer>
	</div> <!-- /container -->
</body>
</html>